### ISSUE TITLE
Example.py Error?????

### ISSUE THREAD

**Issue by Cyber-Shadow** [gunthercox/chatterbot-voice#1]
Traceback (most recent call last):
  File "C:/Users/Craig/PycharmProjects/untitled2/s.py", line 7, in <module>
    "chatterbot_voice.Voice"
  File "C:\Python27\lib\site-packages\chatterbot\chatterbot.py", line 36, in __init__
    self.add_adapter(adapter, **kwargs)
  File "C:\Python27\lib\site-packages\chatterbot\adapters\adaptation.py", line 33, in add_adapter
    adapter = NewAdapter(**kwargs)
  File "C:\Python27\lib\site-packages\chatterbot_voice\voice.py", line 15, in __init__
    subprocess.call(['jack_control', 'start'])
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

--------

This is the error I received after running your example program on  windows (python 2.7.10) after installing chatterbot-voice through pip.

**Comment by gunthercox** [comment]
This error is happening because the program is attempting to start jack_control (`subprocess.call(['jack_control', 'start'])`) which is not a valid command in windows. I will make changes to ensure that this works properly.

**Comment by gunthercox** [comment]
Hi @Cyber-Shadow This should be fixed in version 0.0.2 of chatterbot-voice. Feel free to reopen this ticket if the issue persists.

**Comment by hiradadiamond** [comment]
Traceback (most recent call last):
  File "C:\Python27\chatbot.py", line 14, in <module>
    database="../data.db"
  File "C:\Python27\lib\site-packages\chatterbot\chatterbot.py", line 51, in __init__
    self.storage = StorageAdapterClass(**kwargs)
  File "C:\Python27\lib\site-packages\chatterbot\adapters\storage\jsondatabase.py", line 16, in __init__
    self.database = Database(database_path)
  File "C:\Python27\lib\site-packages\jsondb\db.py", line 13, in __init__
    self.set_path(file_path)
  File "C:\Python27\lib\site-packages\jsondb\db.py", line 21, in set_path
    write_data(file_path, {})
  File "C:\Python27\lib\site-packages\jsondb\file_writer.py", line 21, in write_data
    with open(path, "w+") as db:
IOError: [Errno 13] Permission denied: '../data.db'
 

WHAT IT MEANS???

**Comment by gunthercox** [comment]
Hi @hiradadiamond, I think you have a permission error on your database file. Check out the last line in the traceback you posted:
> IOError: [Errno 13] Permission denied: '../data.db'

You don't appear to have permission to access the file location where `data.db` is being created. Try creating it in a different directory or add permission for your user to access the directory it is being created in.
