### ISSUE TITLE
NameError: global name 'warnings' is not defined

### ISSUE THREAD

**Issue by shashanka300** [gunthercox/chatterbot-voice#10]
/usr/local/lib/python2.7/dist-packages/chatterbot/storage/jsonfile.py:26: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  self.UnsuitableForProductionWarning
Traceback (most recent call last):
  File "ca.py", line 7, in <module>
    output_adapter="chatterbot_voice.VoiceOutput",
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/chatterbot.py", line 38, in __init__
    self.input = utils.initialize_class(input_adapter, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/utils.py", line 33, in initialize_class
    return Class(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot_voice/voice.py", line 22, in __init__
    self.attempt_jack_control_start()
  File "/usr/local/lib/python2.7/dist-packages/chatterbot_voice/voice.py", line 51, in attempt_jack_control_start
    warnings.warn(
NameError: global name 'warnings' is not defined

how to fix it

**Comment by gunthercox** [comment]
Hi @shashanka300 sorry about my late response on this. I've pushed up changes to correct the problem.

The clue in the error message is the line:

```
File "/usr/local/lib/python2.7/dist-packages/chatterbot_voice/voice.py", line 51
...
NameError: global name 'warnings' is not defined
```

The `warnings` package just needed to be imported.

***

I've also opened #11 which adds automatic code style checks and will help to prevent issues like this from occurring again in the future.
